language: "auto"
text_language: "日文"
ref_audio: "/home/yumio/Code/MHCP_Momotalk/TTS/ref_audio/hina1.mp3"
ref_audio_list: null
prompt_text: "先生。今日も全力であなたをアシストしますね。"
prompt_language: "日文"
top_k: 5
top_p: 1
temperature: 0.6
how_to_cut: "凑四句一切"
batch_size: 20
speed_factor: 1.0
ref_text_free: False
split_bucket: True
fragment_interval: 0.3
seed: -1
keep_random: True
parallel_infer: True
repetition_penalty: 1.35
gpt_path: "/home/yumio/Code/MHCP_Momotalk/TTS/GPT_weights_v2/空崎日奈-e10.ckpt"
sovits_path: "/home/yumio/Code/MHCP_Momotalk/TTS/SoVITS_weights_v2/空崎日奈_e10_s90.pth"
cnhubert_base_path: "/home/yumio/Code/MHCP_Momotalk/TTS/GPT_SoVITS/pretrained_models/chinese-hubert-base"
bert_path: "/home/yumio/Code/MHCP_Momotalk/TTS/GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large"
pretrained_sovits_path: "/home/yumio/Code/MHCP_Momotalk/TTS/GPT_SoVITS/pretrained_models/s2G488k.pth"
pretrained_gpt_path: "/home/yumio/Code/MHCP_Momotalk/TTS/GPT_SoVITS/pretrained_models/s1bert25hz-2kh-longer-epoch=68e-step=50232.ckpt"
is_half: "True"
version: "v2"
media_type: "wav"